namespace ResearchLms.Inventory.Application.DTOs;

public record InventoryItemDto(
    Guid Id,
    string SKU,
    string Name,
    string? Description,
    string Category,
    string UnitOfMeasure,
    decimal QuantityOnHand,
    decimal QuantityReserved,
    decimal QuantityAvailable,
    decimal ReorderPoint,
    decimal UnitCost,
    decimal TotalValue,
    string? Barcode,
    string? StorageLocation,
    DateOnly? ExpiryDate,
    bool IsHazardous,
    bool IsLowStock,
    bool IsOutOfStock,
    bool IsExpiringSoon,
    bool IsExpired,
    bool IsActive,
    DateTime UpdatedAt
);

public record InventoryItemDetailDto(
    Guid Id,
    string SKU,
    string Name,
    string? Description,
    string Category,
    string UnitOfMeasure,
    decimal QuantityOnHand,
    decimal QuantityReserved,
    decimal QuantityAvailable,
    decimal ReorderPoint,
    decimal ReorderQuantity,
    decimal UnitCost,
    decimal TotalValue,
    string? Barcode,
    string? StorageLocation,
    DateOnly? ExpiryDate,
    bool IsHazardous,
    bool IsLowStock,
    bool IsOutOfStock,
    bool IsExpiringSoon,
    bool IsExpired,
    bool IsActive,
    Guid? PreferredVendorId,
    string? PreferredVendorName,
    DateTime UpdatedAt,
    IEnumerable<StockTransactionDto> RecentTransactions
);
