namespace ResearchLms.Facilities.Application.DTOs;

public record AssetDto(
    Guid Id,
    string Name,
    string Identifier,
    string Category,
    string AssetType,
    string Status,
    Guid FacilityId,
    string? FacilityName,
    string? Location,
    decimal? CurrentValue,
    string? QrCode);

public record AssetDetailDto(
    Guid Id,
    Guid TenantId,
    string Name,
    string Identifier,
    string Category,
    string AssetType,
    string Status,
    Guid FacilityId,
    string? FacilityName,
    string? Model,
    string? Manufacturer,
    DateOnly? AcquisitionDate,
    decimal? AcquisitionCost,
    decimal? CurrentValue,
    decimal? SalvageValue,
    int? UsefulLifeYears,
    string? DepreciationMethod,
    string? Location,
    Dictionary<string, string> CustomFields,
    string? QrCode,
    string? RfidTag,
    DateTime CreatedAt,
    DateTime? UpdatedAt,
    // Instrument-specific (null when AssetType != "Instrument")
    string? IpAddress,
    int? Port,
    string? ConnectionProtocol,
    string? Firmware,
    DateOnly? LastCalibrationDate,
    DateOnly? NextCalibrationDate,
    int? MaintenanceIntervalDays,
    bool IotEnabled);

public record CreateAssetRequest(
    string Name,
    string Identifier,
    string Category,
    Guid FacilityId,
    string? Model,
    string? Manufacturer,
    DateOnly? AcquisitionDate,
    decimal? AcquisitionCost,
    decimal? SalvageValue,
    int? UsefulLifeYears,
    string? DepreciationMethod,
    string? Location,
    Dictionary<string, string>? CustomFields,
    string? QrCode,
    string? RfidTag,
    // Instrument-specific
    string? IpAddress,
    int? Port,
    string? ConnectionProtocol,
    string? Firmware,
    DateOnly? LastCalibrationDate,
    DateOnly? NextCalibrationDate,
    int? MaintenanceIntervalDays,
    bool IotEnabled = false);

public record UpdateAssetRequest(
    string Name,
    string? Model,
    string? Manufacturer,
    DateOnly? AcquisitionDate,
    decimal? AcquisitionCost,
    decimal? SalvageValue,
    int? UsefulLifeYears,
    string? DepreciationMethod,
    string? Location,
    Dictionary<string, string>? CustomFields,
    string? QrCode,
    string? RfidTag,
    // Instrument-specific
    string? IpAddress,
    int? Port,
    string? ConnectionProtocol,
    string? Firmware,
    DateOnly? LastCalibrationDate,
    DateOnly? NextCalibrationDate,
    int? MaintenanceIntervalDays,
    bool IotEnabled = false);

public record AssetSearchParams(
    string? Query,
    string? Category,
    string? Status,
    Guid? FacilityId,
    string? Location,
    string? CustomFieldKey,
    string? CustomFieldValue,
    int Page = 1,
    int PageSize = 20);
